Update Logo

diff --git a/system_files/overrides/usr/bin/dnf b/system_files/overrides/usr/bin/dnf
--- a/system_files/overrides/usr/bin/dnf
+++ b/system_files/overrides/usr/bin/dnf
@@ -8,8 +8,8 @@ fi
 # Show the error if we attempt to use the install/uninstall commands
 for arg in "$@"; do
     if [[ $arg == "install" || $arg == "in" || $arg == "remove" || $arg == "rm" ]]; then
-        echo -e "ERROR: Fedora Atomic images utilize rpm-ostree instead (and is discouraged to use).\nPlease, \e]8;;https://docs.agungos.gg/Installing_and_Managing_Software/\aread our documentation\e]8;;\a\n\e]8;;https://docs.agungos.gg/Installing_and_Managing_Software/\ahttps://docs.agungos.gg/Installing_and_Managing_Software/\e]8;;\a\n" >&2
-        ${SUDO_USER:+sudo -u $SUDO_USER dbus-launch} bash -lc 'xdg-open "https://docs.agungos.gg/Installing_and_Managing_Software" 2> /dev/null'
+        echo -e "ERROR: Fedora Atomic images utilize rpm-ostree instead (and is discouraged to use).\nPlease, \e]8;;https://docs.os.agungdev.com/Installing_and_Managing_Software/\aread our documentation\e]8;;\a\n\e]8;;https://docs.os.agungdev.com/Installing_and_Managing_Software/\ahttps://docs.os.agungdev.com/Installing_and_Managing_Software/\e]8;;\a\n" >&2
+        ${SUDO_USER:+sudo -u $SUDO_USER dbus-launch} bash -lc 'xdg-open "https://docs.os.agungdev.com/Installing_and_Managing_Software" 2> /dev/null'
         exit 1
     fi
 done
